
@startuml
hide circle
skinparam linetype ortho
skinparam shadowing false
skinparam entity {
BackgroundColor<<Fact>> #FDF6E3
BackgroundColor<<Dimension>> #E6F7FF
}

entity "fact_averagecosts_dlm" <<fact>> {
    * fscldt_id
		sku_id
		average_unit_standardcost
		average_unit_landedcost
}
entity "fact_transactions_dlm" <<fact>> {
    * order_id
		line_id
		type
		dt
		pos_site_id
		sku_id
		fscldt_id
		price_substate_id
		sales_units
		sales_dollars
		discount_dollars
		original_order_id
		original_line_id
}
entity "hier_clnd_dlm" <<hier>> {
    * fscldt_id
		fscldt_label
		fsclwk_id
		fsclwk_label
		fsclmth_id
		fsclmth_label
		fsclqrtr_id
		fsclqrtr_label
		fsclyr_id
		fsclyr_label
		ssn_id
		ssn_label
		ly_fscldt_id
		lly_fscldt_id
		fscldow
		fscldom
		fscldoq
		fscldoy
		fsclwoy
		fsclmoy
		fsclqoy
		date
}
entity "hier_hldy_dlm" <<hier>> {
    * hldy_id
		hldy_label
}
entity "hier_invloc_dlm" <<hier>> {
    * loc
		loc_label
		loctype
		loctype_label
}
entity "hier_invstatus_dlm" <<hier>> {
    * code_id
		code_label
		bckt_id
		bckt_label
		ownrshp_id
		ownrshp_label
}
entity "hier_possite_dlm" <<hier>> {
    * site_id
		site_label
		subchnl_id
		subchnl_label
		chnl_id
		chnl_label
}
entity "hier_pricestate_dlm" <<hier>> {
    * substate_id
		substate_label
		state_id
		state_label
}
entity "hier_prod_dlm" <<hier>> {
    * sku_id
		sku_label
		stylclr_id
		stylclr_label
		styl_id
		styl_label
		subcat_id
		subcat_label
		cat_id
		cat_label
		dept_id
		dept_label
		issvc
		isasmbly
		isnfs
}
entity "hier_rtlloc_dlm" <<hier>> {
    * str
		str_label
		dstr
		dstr_label
		rgn
		rgn_label
}@enduml